# Guest House Management System - Complete Configuration
# PostgreSQL Database, Logging & Image Upload

server:
  port: 8080

spring:
  application:
    name: guest-house-management

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/sotsamban_guesthouse_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # Static Resource Handling for Images
  web:
    resources:
      static-locations:
        - file:uploads/
        - classpath:/static/
      add-mappings: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

# Application-Specific Configuration
app:
  upload:
    dir: uploads/
  base:
    url: http://localhost:8080

# Logging Configuration (Optional)
logging:
  level:
    com.sotsamban.guesthouse: INFO
    org.springframework.web.multipart: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
